#!/bin/bash
# /Created By: Charles Engen
# 10/7/2016
# Script reverts settings back to original from ad-hoc mode

echo "Starting Ad-hoc mode"

sudo ifdown wlan0

sudo cp /etc/network/interface-adhoc /etc/network/interface
sudo cp /etc/default/ifplugd-adhoc /etc/default/ifplugd

sudo ifup wlan0
